### ISSUE TITLE
`sw-operator` isn't working in v1.1.0-b1

### ISSUE THREAD

**Issue by jclapis** [nodeset-org/hyperdrive#144]
**Describe the bug**
The `sw-operator` container is erroring out quickly after starting in Beta 1 with the error message `'NoneType' object has no attribute 'config'`.

**To Reproduce**
1. Run `hyperdrive s s`
2. Run `hyperdrive s l sw_operator`
3. Behold, 'tis broken.

**Expected behavior**
It should be running normally.
